[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
monitor_filters = log2file
board_build.filesystem_size = 64K
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D DISABLE_SERIAL=1
    -D DISABLE_SERIALEVENT=1
    -D CORE_DEBUG_LEVEL=0
    -D ARDUHAL_LOG_LEVEL=0
    -D USE_TINYUSB
    -D Serial=Serial2
lib_deps = 
    mikalhart/TinyGPSPlus@^1.0.3
    mprograms/QMC5883LCompass@^1.1.1
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/Adafruit HMC5883 Unified@^1.2.1
    DNSServer
    # h2zero/NimBLE-Arduino
    olikraus/U8g2@^2.34.22
    m5stack/M5Unified